config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  root "kittens#index", as: :root
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
# frozen_string_literal: true

class Kitten < ApplicationRecord
  validates :name, :age, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
# frozen_string_literal: true

class KittensController < ApplicationController
  before_action :set_kitten, only: %i[show edit update destroy]

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render xml: @kittens }
      format.json { render json: @kittens }
    end
  end

  def show
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render xml: @kitten }
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    respond_to do |format|
      if @kitten.save
        format.html { redirect_to :root, notice: 'Kitten was successfully created.' }
        format.json { render :show, status: :created, location: @kitten }
      else
        format.html { redirect_to :root, alert: 'Kitten not created' }
        format.json { render json: @kitten.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @kitten.update(kitten_params)
        format.html { redirect_to @kitten, notice: 'Kitten was successfully updated.' }
        format.json { render :show, status: :ok, location: @kitten }
      else
        format.html { render :edit }
        format.json { render json: @kittn.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @kitten.destroy
    respond_to do |format|
      format.html { redirect_to :root, notice: 'Kitten was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
end

private
def kitten_params
  params.require(:kitten).permit(:name, :age, :cuteness, :softness)
end

def set_kitten
  @kitten = Kitten.find(params[:id])
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/kittens_helper.rb
# frozen_string_literal: true

module KittensHelper
end

app/views/kittens/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@kitten) do |f| %>
      <% render 'shared/error_messages', object: f.object %> <br>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %><br>

      <%= f.label :age %>
      <%= f.number_field :age, class: 'form-control' %><br>

      <%= f.label :cuteness %>
      <%= f.text_field :cuteness, class: 'form-control' %><br>

      <%= f.label :softness %>
      <%= f.text_field :softness, class: 'form-control' %><br>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>

<%= render 'form' =%>

<%= link_to "delete kitten", @kitten, method: :delete=%>

app/views/kittens/index.html.erb
<h1> this is index page <h1>
<h2> All kittens </h2>
<h3> <%= link_to "Create a new kitten", new_kitten_path =%>
<ul>
  <% @kittens.each do |kitten| %>
    <li> <%= link_to kitten.name, kitten=%> <%= link_to "delete kitten", kitten, method: :delete=%></li>
  <% end %>
</ul>
  

app/views/kittens/new.html.erb
<h1>Create a new Kitten</h1>

<%= render 'form' =%>

app/views/kittens/show.html.erb
<h1> Show a Kitten </h1>
<div class="row">
    <section class="kitten_info">
        <ul>
        <li> <%= @kitten.name %> </li>
        <li> <%= @kitten.age %> </li>
        <li> <%= @kitten.cuteness %> </li>
        <li> <%= @kitten.softness %> </li> 
        </ul>
        <%= link_to "delete kitten", @kitten, method: :delete=%>
    </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OthmanKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>